# Site settings
title: Elements
email: 
url: http://127.0.0.1:4000/
description: 
baseurl: 

# Footer settings
footer: Student | Copyright 2017 


# Build settings
markdown: kramdown
permalink: pretty